name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Login to a registry
        run: echo ${{ secrets.DOCKER_HUB_TOKEN }} | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

      - name: Run build
        run: ./build.sh latest
